*makefile.txt*

==============================================================================
                                                                  *makefile-help*
$@ - The file name of the target
$< - The name of the first dependency
$* - The part of a filename which matched a suffix rule
$? - The names of all the dependencies newer than the target separated by spaces
$^ - The names of all the dependencies separated by spaces, but with duplicate names removed
$+ - The names of all the dependencies separated by spaces with duplicated names included and in the same order as in the rule
==============================================================================
                                                                  *makefile-examples*
CC = gcc

CFLAGS = -g -Wall -pedantic

PROGRAM = hex_read
OBJ = plaintext.o hex_read.o

default: $(addsuffix .bin,$(PROGRAM))
	./hex_read.bin

%.bin: $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^

%.o: %.S
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean: 
	rm -f *.o
==============================================================================
