"$schema" = "https://starship.rs/config-schema.json"

format = """
[░▒▓](os_bg)\
$os\
$username\
[](bg:dir_bg fg:os_bg)\
$directory\
[](fg:dir_bg bg:git_bg)\
$git_branch\
$git_status\
[](fg:git_bg bg:lang_bg)\
$nodejs\
$rust\
$golang\
$python\
[](fg:lang_bg bg:background)\
$character"""

add_newline = false

continuation_prompt = '▶▶ '

palette = "carbonfox"

[palettes.carbonfox]
red = "#ee5396"
green = "#25be6a"
purple = "#be95ff"
yellow = "#08bdba"
os_bg = "#7b7c7e"
os_fg = "#0c0c0c"
dir_bg = "#25be6a"
dir_fg = "#161616"
git_bg = "#08bdba"
git_fg = "#252525"
lang_bg = "#78a9ff"
lang_fg = "#353535"

[os]
disabled = false
style = "bg:os_bg fg:os_fg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = " 󰣭 "
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:os_bg fg:os_fg"
style_root = "bg:os_bg fg:os_fg"
format = "[ $user ]($style)"

[directory]
style = "fg:dir_fg bg:dir_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"src" = " "

[git_branch]
symbol = ""
style = "bg:git_bg"
format = '[[ $symbol $branch ](fg:git_fg bg:git_bg)]($style)'

[git_status]
style = "bg:git_bg"
format = '[[($all_status$ahead_behind )](fg:git_fg bg:git_bg)]($style)'

[nodejs]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[c]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[rust]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[golang]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[php]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[java]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[kotlin]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[haskell]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[python]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) (\($virtualenv\))](fg:lang_fg bg:lang_bg)]($style)'

[character]
disabled = false
success_symbol = '[](bold fg:#25be6a)'
error_symbol = '[](bold fg:#ee5396)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
